### ISSUE TITLE
Objectbox is open source, why can't we find the source code?

### ISSUE THREAD

**Issue by Laganer** [objectbox/objectbox-c#6]

**Comment by malkia** [comment]
In the headers the API looks very closely to the mdb_ one (lmdb), but I can't find this wrapper anywhere (maybe that's the commercial part?)

**Comment by obx-vivien** [comment]
ObjectBox bindings are open sourced under Apache 2.0; accessing the ObjectBox core is possible with a commercial licence that also includes support. The reason is that it is mainly big B2B IoT users that need access and support - and these customers allow us to maintain ObjectBox DB free to use for (almost) everyone else.
